<?php

/**
 * BasePlanTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property boolean $visible
 * @property integer $width
 * @property integer $height
 * @property integer $background_id
 * @property PlanTableImage $PlanTableBackground
 * @property Doctrine_Collection $PlanTableObject
 * 
 * @method string              getName()                Returns the current record's "name" value
 * @method string              getDescription()         Returns the current record's "description" value
 * @method boolean             getVisible()             Returns the current record's "visible" value
 * @method integer             getWidth()               Returns the current record's "width" value
 * @method integer             getHeight()              Returns the current record's "height" value
 * @method integer             getBackgroundId()        Returns the current record's "background_id" value
 * @method PlanTableImage      getPlanTableBackground() Returns the current record's "PlanTableBackground" value
 * @method Doctrine_Collection getPlanTableObject()     Returns the current record's "PlanTableObject" collection
 * @method PlanTable           setName()                Sets the current record's "name" value
 * @method PlanTable           setDescription()         Sets the current record's "description" value
 * @method PlanTable           setVisible()             Sets the current record's "visible" value
 * @method PlanTable           setWidth()               Sets the current record's "width" value
 * @method PlanTable           setHeight()              Sets the current record's "height" value
 * @method PlanTable           setBackgroundId()        Sets the current record's "background_id" value
 * @method PlanTable           setPlanTableBackground() Sets the current record's "PlanTableBackground" value
 * @method PlanTable           setPlanTableObject()     Sets the current record's "PlanTableObject" collection
 * 
 * @package    LiveOrder
 * @subpackage model
 * @author     Adrien Bokor <adrien@bokor.be>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePlanTable extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('plan_table');
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 100,
             ));
        $this->hasColumn('description', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('visible', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('width', 'integer', null, array(
             'type' => 'integer',
             'default' => 1024,
             ));
        $this->hasColumn('height', 'integer', null, array(
             'type' => 'integer',
             'default' => 689,
             ));
        $this->hasColumn('background_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PlanTableImage as PlanTableBackground', array(
             'local' => 'background_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('PlanTableObject', array(
             'local' => 'id',
             'foreign' => 'plantable_id'));
    }
}