<?php

/**
 * BaseCategoryImprimante
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $category_id
 * @property integer $imprimante_id
 * @property Imprimante $Imprimante
 * @property Category $Category
 * 
 * @method integer            getCategoryId()    Returns the current record's "category_id" value
 * @method integer            getImprimanteId()  Returns the current record's "imprimante_id" value
 * @method Imprimante         getImprimante()    Returns the current record's "Imprimante" value
 * @method Category           getCategory()      Returns the current record's "Category" value
 * @method CategoryImprimante setCategoryId()    Sets the current record's "category_id" value
 * @method CategoryImprimante setImprimanteId()  Sets the current record's "imprimante_id" value
 * @method CategoryImprimante setImprimante()    Sets the current record's "Imprimante" value
 * @method CategoryImprimante setCategory()      Sets the current record's "Category" value
 * 
 * @package    LiveOrder
 * @subpackage model
 * @author     Adrien Bokor <adrien@bokor.be>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategoryImprimante extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category_imprimante');
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('imprimante_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Imprimante', array(
             'local' => 'imprimante_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}