<?php

/**
 * BasePlanTableImageCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $PlanTableImage
 * 
 * @method string                 getName()           Returns the current record's "name" value
 * @method Doctrine_Collection    getPlanTableImage() Returns the current record's "PlanTableImage" collection
 * @method PlanTableImageCategory setName()           Sets the current record's "name" value
 * @method PlanTableImageCategory setPlanTableImage() Sets the current record's "PlanTableImage" collection
 * 
 * @package    LiveOrder
 * @subpackage model
 * @author     Adrien Bokor <adrien@bokor.be>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePlanTableImageCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('plan_table_image_category');
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('PlanTableImage', array(
             'local' => 'id',
             'foreign' => 'category_id'));
    }
}