<?php

/**
 * BaseSupplement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property float $fois_prix
 * @property float $plus_prix
 * @property integer $is_publish
 * @property integer $category_id
 * @property Doctrine_Collection $ArticleCommandes
 * @property Category $Category
 * @property Doctrine_Collection $ArticleSupplement
 * 
 * @method string              getName()              Returns the current record's "name" value
 * @method float               getFoisPrix()          Returns the current record's "fois_prix" value
 * @method float               getPlusPrix()          Returns the current record's "plus_prix" value
 * @method integer             getIsPublish()         Returns the current record's "is_publish" value
 * @method integer             getCategoryId()        Returns the current record's "category_id" value
 * @method Doctrine_Collection getArticleCommandes()  Returns the current record's "ArticleCommandes" collection
 * @method Category            getCategory()          Returns the current record's "Category" value
 * @method Doctrine_Collection getArticleSupplement() Returns the current record's "ArticleSupplement" collection
 * @method Supplement          setName()              Sets the current record's "name" value
 * @method Supplement          setFoisPrix()          Sets the current record's "fois_prix" value
 * @method Supplement          setPlusPrix()          Sets the current record's "plus_prix" value
 * @method Supplement          setIsPublish()         Sets the current record's "is_publish" value
 * @method Supplement          setCategoryId()        Sets the current record's "category_id" value
 * @method Supplement          setArticleCommandes()  Sets the current record's "ArticleCommandes" collection
 * @method Supplement          setCategory()          Sets the current record's "Category" value
 * @method Supplement          setArticleSupplement() Sets the current record's "ArticleSupplement" collection
 * 
 * @package    LiveOrder
 * @subpackage model
 * @author     Adrien Bokor <adrien@bokor.be>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSupplement extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('supplement');
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('fois_prix', 'float', null, array(
             'type' => 'float',
             'default' => 1,
             ));
        $this->hasColumn('plus_prix', 'float', null, array(
             'type' => 'float',
             'default' => 0,
             ));
        $this->hasColumn('is_publish', 'integer', null, array(
             'type' => 'integer',
             'default' => 1,
             ));
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ArticleCommande as ArticleCommandes', array(
             'refClass' => 'ArticleCommandeSupplement',
             'local' => 'supplement_id',
             'foreign' => 'article_commande_id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('ArticleCommandeSupplement as ArticleSupplement', array(
             'local' => 'id',
             'foreign' => 'supplement_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->actAs($sluggable0);
    }
}