<?php

/**
 * BaseArticleElement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $article_id
 * @property integer $element_id
 * @property float $a_deduire
 * @property Article $Article
 * @property Element $Element
 * 
 * @method integer        getArticleId()  Returns the current record's "article_id" value
 * @method integer        getElementId()  Returns the current record's "element_id" value
 * @method float          getADeduire()   Returns the current record's "a_deduire" value
 * @method Article        getArticle()    Returns the current record's "Article" value
 * @method Element        getElement()    Returns the current record's "Element" value
 * @method ArticleElement setArticleId()  Sets the current record's "article_id" value
 * @method ArticleElement setElementId()  Sets the current record's "element_id" value
 * @method ArticleElement setADeduire()   Sets the current record's "a_deduire" value
 * @method ArticleElement setArticle()    Sets the current record's "Article" value
 * @method ArticleElement setElement()    Sets the current record's "Element" value
 * 
 * @package    LiveOrder
 * @subpackage model
 * @author     Adrien Bokor <adrien@bokor.be>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArticleElement extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('article_element');
        $this->hasColumn('article_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('element_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('a_deduire', 'float', null, array(
             'type' => 'float',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Article', array(
             'local' => 'article_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Element', array(
             'local' => 'element_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}