<?php

/**
 * BaseFournisseur
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $tel
 * @property Doctrine_Collection $Element
 * 
 * @method string              getName()    Returns the current record's "name" value
 * @method string              getTel()     Returns the current record's "tel" value
 * @method Doctrine_Collection getElement() Returns the current record's "Element" collection
 * @method Fournisseur         setName()    Sets the current record's "name" value
 * @method Fournisseur         setTel()     Sets the current record's "tel" value
 * @method Fournisseur         setElement() Sets the current record's "Element" collection
 * 
 * @package    LiveOrder
 * @subpackage model
 * @author     Adrien Bokor <adrien@bokor.be>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFournisseur extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('fournisseur');
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 100,
             ));
        $this->hasColumn('tel', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Element', array(
             'local' => 'id',
             'foreign' => 'fournisseur_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}