<?php

/**
 * BaseStatutCommande
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $realId
 * @property Doctrine_Collection $Commande
 * 
 * @method string              getName()     Returns the current record's "name" value
 * @method integer             getRealId()   Returns the current record's "realId" value
 * @method Doctrine_Collection getCommande() Returns the current record's "Commande" collection
 * @method StatutCommande      setName()     Sets the current record's "name" value
 * @method StatutCommande      setRealId()   Sets the current record's "realId" value
 * @method StatutCommande      setCommande() Sets the current record's "Commande" collection
 * 
 * @package    LiveOrder
 * @subpackage model
 * @author     Adrien Bokor <adrien@bokor.be>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStatutCommande extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('statut_commande');
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 100,
             ));
        $this->hasColumn('realId', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Commande', array(
             'local' => 'id',
             'foreign' => 'statut_id'));
    }
}