<?php

/**
 * ArticleCommandeSupplementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArticleCommandeSupplementTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArticleCommandeSupplementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ArticleCommandeSupplement');
    }
}