<?php

/**
 * ArticleCommandeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArticleCommandeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArticleCommandeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ArticleCommande');
    }
}