<?php

/**
 * ArticleElementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ArticleElementTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ArticleElementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ArticleElement');
    }
}