<?php

/**
 * CategoryImprimanteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoryImprimanteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoryImprimanteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CategoryImprimante');
    }
}