<?php

/**
 * ClotureTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClotureTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClotureTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cloture');
    }
}