<?php

/**
 * ConditionnementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConditionnementTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConditionnementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Conditionnement');
    }
}