<?php

/**
 * GroupeReductionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GroupeReductionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GroupeReductionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GroupeReduction');
    }
}