<?php

/**
 * ImprimanteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ImprimanteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ImprimanteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Imprimante');
    }
}