<?php

/**
 * PlanTableTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlanTableTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlanTableTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlanTable');
    }
}