<?php

/**
 * PlanTableObjectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlanTableObjectTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlanTableObjectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlanTableObject');
    }
}