<?php

/**
 * PlanTableImageCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlanTableImageCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlanTableImageCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlanTableImageCategory');
    }
}