<?php

/**
 * PlanTableImageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlanTableImageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlanTableImageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlanTableImage');
    }
}