<?php

/**
 * PubliciteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PubliciteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PubliciteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Publicite');
    }
}