<?php

/**
 * StatutCommandeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StatutCommandeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StatutCommandeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StatutCommande');
    }
}