<?php

/**
 * SupplementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SupplementTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SupplementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Supplement');
    }
}