# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [style.css, stylesheet.css, main.css, jquery.autocomplete.css, jquery.gritter.css, bootstrap.css, jquery.multiselect.css, prettyPhoto.css, preloadify.css ]

  javascripts:    [script.js, hoverIntent.js, superfish.js, jquery.prettyPhoto.js, interface.js, jquery.gritter.min.js, thumbs.js, bootstrap.min.js, jquery.multiselect.js, jquery.preloadify.min.js ]

  has_layout:     true
  layout:         layout
  