all:  
  storage:
     class: sfCacheSessionStorage
     param:
      session_name: LiveOrder #[required] name of session to use
      session_cookie_path: / #[required] cookie path
      session_cookie_lifetime: +30 days #[required] liftime of cookie
      session_cookie_secure: false #[required] send only if secure connection
      session_cookie_http_only: false #[required] accessible only via http protocol
      cache:
        class: sfAPCCache
        param: ~
  
