<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('sf_guard_user', 'group_id');
        $this->changeColumn('sf_guard_user', 'email_address', 'string', '255', array(
             ));
    }

    public function down()
    {
        $this->addColumn('sf_guard_user', 'group_id', 'integer', '8', array(
             ));
    }
}